version: '3'
services:
  server:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - '5016:80'
    environment:
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - SERVER_APIKEY=${SERVER_APIKEY}