version: '3'
services:
  server:
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - '5016:80'
    environment:
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - SERVER_APIKEY=${SERVER_APIKEY}
    volumes:
      - logs:/var/lib/coypos/logs
  admin:
    build:
      context: coyposadmin/
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - '8081:8080'
volumes:
  logs: